[model.AstroMiNN]
num_classes = 5
num_mlp_experts = 4

towers_hidden_dims = 16
towers_outdims = 32

fusion_hidden_dims = 128
fusion_router_dims = 128
fusion_outdims = 32

[model.SpectraNet]
redshift = false
depths = [1, 1, 1, 1, 1]
# need an actual default for this
class_order = 9
