[model.AstroMiNN]
num_classes = 9
num_mlp_experts = 4

towers_hidden_dims = 16
towers_outdims = 32

fusion_hidden_dims = 128
fusion_router_dims = 128
fusion_outdims = 32

[data_set.ImageAndMetadataDataset]
alert = 0  # defines the maximum number of alerts per sample to work with. Use <= 0 for all available alerts.
all_samples = false
augment = true
classes = [['SN Ia','SN Ic','SN Ib'],[ 'SN IIP', 'SN IIn','SN II'], ['Cataclysmic'], ['AGN'], ['Tidal Disruption Event']]
cutout_size = 63
image_norm = false  #? What should the default be here?
patch_size = [32, 32]  #? Is it possible to consolidate this with cutout_size?
tags = []
