[model]
name = "applecider.models.astrominn.AstroMiNN"

[data_set]
train_size = 0.8
validate_size = 0.2
test_size = 0.0

[model_inputs]
[model_inputs.train.data]
dataset_class = "applecider.datasets.image_and_metadata_dataset.ImageAndMetadataDataset"
data_location = "../../../data/preprocessed_ztf_alerts"
fields = ["image", "metadata", "target", "obj_id"]
primary_id_field = "obj_id"

[model_inputs.infer.data]
dataset_class = "applecider.datasets.image_and_metadata_dataset.ImageAndMetadataDataset"
data_location = "../../../data/ztf23_processed_data"
fields = ["image", "metadata", "target", "obj_id"]
primary_id_field = "obj_id"

[data_set.ImageAndMetadataDataset]
class_distribution = [0.3, 0.1, 0.1, 0.3, 0.1]