[model]
name = "AppleCider.models.hyrax_models.astrominn.AstroMiNN"

[model_inputs]
[model_inputs.data]
dataset_class = "AppleCider.datasets.hyrax_datasets.image_and_metadata_dataset.ImageAndMetadataDataset"
data_location = "../../data/preprocessed_ztf_alerts"
primary_id_field = "obj_id"
