[model]
name = "applecider.models.HyraxBaselineCLS.HyraxBaselineCLS"

[data_loader]
batch_size = 5
collate_fn = "applecider.datasets.photo_dataset.collate"

[data_set.PhotoEventsDataset]
manifest_path = "/Users/dbranton/lincc/incubators/photo_events/manifest_train.csv"
stats_path = "/Users/dbranton/lincc/incubators/photo_events/feature_stats_day100.npz"

[model_inputs]
[model_inputs.train.data]
dataset_class = "applecider.datasets.photo_dataset.PhotoEventsDataset"
data_location = "/Users/dbranton/lincc/incubators/photo_events/train/"
fields = ["photometry", "label", "mean", "std"]
primary_id_field = "object_id"

[model_inputs.infer.data]
dataset_class = "applecider.datasets.photo_dataset.PhotoEventsDataset"
data_location = "/Users/dbranton/lincc/incubators/photo_events/test/"
#data_location = "/work/hdd/bcrv/ffontinelenunes/data/applecider/photo_events/test/"
fields = ["photometry", "label", "mean", "std"]
primary_id_field = "object_id"

[train]
#The number of epochs to train for.
epochs = 2

[optimizer]
name = "torch.optim.Adam"