[model]
name = "applecider.models.HyraxBaselineCLS.HyraxBaselineCLS"

[model.HyraxBaselineCLS]
use_probabilities = false

[data_loader]
batch_size = 128
collate_fn = "applecider.datasets.photo_dataset.collate"

# [data_set.PhotoEventsDataset]
# manifest_path = "../../../data/photo_events/manifest_train.csv"

# Needed for manifest path -- hyrax will fix
[data_set."applecider.datasets.photo_dataset.PhotoEventsDataset"]
manifest_path = "../../../data/photo_events/manifest_train.csv"
stats_path = "../../../data/photo_events/feature_stats_day100.npz"
horizon = 100.0 # days
ideal_class_distribution = [0.3,0.1,0.1,0.3,0.1]
use_oversampling = true

[model_inputs]
[model_inputs.train.data]
dataset_class = "applecider.datasets.photo_dataset.PhotoEventsDataset"
data_location = "../../../data/photo_events/train/"
fields = ["photometry", "label", "mean", "std"]
primary_id_field = "object_id"
[model_inputs.train.data.dataset_config]
manifest_path = "../../../data/photo_events/manifest_train.csv"

[model_inputs.validate.data]
#[model_inputs.dont_use.data]
dataset_class = "applecider.datasets.photo_dataset.PhotoEventsDataset"
data_location = "../../../data/photo_events/val/"
fields = ["photometry", "label", "mean", "std"]
primary_id_field = "object_id"
[model_inputs.validate.data.dataset_config]
manifest_path = "../../../data/photo_events/manifest_val.csv"

[model_inputs.infer.data]
dataset_class = "applecider.datasets.photo_dataset.PhotoEventsDataset"
data_location = "../../../data/photo_events/test/"
fields = ["photometry", "mean", "std"]
primary_id_field = "object_id"
[model_inputs.infer.data.dataset_config]
manifest_path = "../../../data/photo_events/manifest_test.csv"
use_oversampling = false

[train]
epochs = 30

[optimizer]
name = "torch.optim.Adam"
lr = 0.0001