[model]
name = "applecider.models.spectranet.SpectraNet"

[model_inputs]

# Note - the sub-table (model_inputs.train.<sub-table>) can be named anything you like.

[model_inputs.train.data]
dataset_class = "applecider.datasets.spectra_dataset.SpectraData"
fields = ["flux", "label", "redshift"]
data_location = "../../../data/spectra_data/train.pt"

[model_inputs.infer.data]
dataset_class = "applecider.datasets.spectra_dataset.SpectraData"
fields = ["flux"]
data_location = "../../../data/spectra_data/test.pt"
primary_id_field = "object_id"

[train]
epochs = 1

[model.SpectraNet]
redshift = true