[model]
name = "AppleCider.models.hyrax_models.HyraxBaselineCLS.HyraxBaselineCLS"

[data_loader]
batch_size = 5
collate_fn = "AppleCider.models.hyrax_models.photo_dataset.collate"

[data_set]
manifest_path = "/Users/dbranton/lincc/incubators/photo_events/manifest_train.csv"

[optimizer]
name = "torch.optim.Adam"